server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db.prrrrrqxvtzvmvqekuly.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: Hhui040506!.
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.qms.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: QMS2026!SuperSecretKeyForJWT512BitsLongEnough1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration: 86400000

app:
  frontend-url: https://qmsfree-d5ggt51srb04b1a65-1440243146.tcloudbaseapp.com/#/student/query
  robot-webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ba15fa98-8864-44fc-89ca-b66a0a5d2dd1

logging:
  level:
    com.example.qms.mapper: DEBUG